import type { Router } from "express";
import { accountRouter } from "./account.js";
import { audioFitRouter } from "./audio-fit.js";
import { audioMixRouter } from "./audio-mix.js";
import { assetGraphRouter } from "./asset-graph.js";
import { assetsRouter } from "./assets.js";
import { beatsRouter } from "./beats.js";
import { briefRouter } from "./brief.js";
import { catalogProtectedRouter } from "./catalog.js";
import { creditsRouter } from "./credits.js";
import { evalRouter } from "./eval.js";
import { generatedAssetsRouter } from "./generated-assets.js";
import { manualTestsRouter } from "./manual-tests.js";
import { meRouter } from "./me.js";
import { miscCapabilitiesRouter } from "./misc-capabilities.js";
import { orchestratorRunsRouter } from "./orchestrator-runs.js";
import { planRouter } from "./plan.js";
import { providerApiKeysRouter } from "./provider-api-keys.js";
import { projectsRouter } from "./projects.js";
import { storyboardsRouter } from "./storyboards.js";
import { studioDraftsRouter } from "./studio-drafts.js";
import { timelinesRouter } from "./timelines.js";
import { workspaceModelSettingsRouter } from "./workspace-model-settings.js";
import { workspacesRouter } from "./workspaces.js";

export function mountProtectedV1Routes(v1: Router) {
  v1.use(accountRouter);
  v1.use(meRouter);
  v1.use(projectsRouter);
  v1.use(workspacesRouter);
  v1.use(audioFitRouter);
  v1.use(audioMixRouter);
  v1.use(assetGraphRouter);
  v1.use(assetsRouter);
  v1.use(beatsRouter);
  v1.use(briefRouter);
  v1.use(catalogProtectedRouter);
  v1.use(creditsRouter);
  v1.use(manualTestsRouter);
  v1.use(miscCapabilitiesRouter);
  v1.use(planRouter);
  v1.use(providerApiKeysRouter);
  v1.use(storyboardsRouter);
  v1.use(orchestratorRunsRouter);
  v1.use(studioDraftsRouter);
  v1.use(timelinesRouter);
  v1.use(workspaceModelSettingsRouter);
  v1.use(evalRouter);
  v1.use(generatedAssetsRouter);
}
