import assert from "node:assert/strict";
import test from "node:test";

import { regenerateImageAsset } from "../regenerate-asset";
import { ApiError } from "../errors";
import type { RegeneratedAssetMedia, V1Asset } from "../store";

function imageAsset(overrides: Partial<V1Asset> = {}): V1Asset {
  return {
    id: "11111111-1111-4111-8111-111111111111",
    schemaVersion: "asset.v1",
    workspaceId: "ws-1",
    projectId: "proj-1",
    kind: "image",
    filename: "old.png",
    status: "ready",
    source: { type: "generated", generatedAssetId: "" },
    visibility: "public",
    createdAt: "2026-06-20T00:00:00.000Z",
    updatedAt: "2026-06-20T00:00:00.000Z",
    provenance: { provider: "openai", model: "gpt-image-1.5", prompt: "a saved prompt" },
    ...overrides,
  } as V1Asset;
}

function makeDeps(asset: V1Asset, effectiveVisibility: "public" | "private" = "public") {
  const calls: {
    generateImage?: { provider: string; model?: string; prompt: string };
    writeObject?: { assetId: string; filename: string; visibility: string };
    applyMedia?: { assetId: string; update: RegeneratedAssetMedia };
  } = {};
  return {
    calls,
    deps: {
      getAsset: async () => asset,
      resolveVisibility: async () => effectiveVisibility,
      generateImage: async (input: { provider: string; model?: string; prompt: string }) => {
        calls.generateImage = input;
        return {
          kind: "image" as const,
          bytes: Buffer.from("png-bytes"),
          extension: "png",
          mimeType: "image/png",
          provider: "openai" as const,
          model: "gpt-image-1.5",
          prompt: input.prompt,
        };
      },
      writeObject: async (input: {
        assetId: string;
        filename: string;
        visibility: string;
      }) => {
        calls.writeObject = {
          assetId: input.assetId,
          filename: input.filename,
          visibility: input.visibility,
        };
        return {
          storageKey: `ws-1/proj-1/${input.assetId}/${input.filename}`,
          storageBucket:
            input.visibility === "private"
              ? "popcornready-assets-private"
              : "popcornready-assets-public",
          contentType: "image/png",
        };
      },
      applyMedia: async (
        _workspaceId: string,
        assetId: string,
        update: RegeneratedAssetMedia
      ) => {
        calls.applyMedia = { assetId, update };
        return {
          url: "https://cdn.example/new.png",
          thumbnailUrl: "https://cdn.example/new.png",
          expiresAt: "2026-06-20T01:00:00.000Z",
        };
      },
    },
  };
}

test("regenerates from the saved prompt as a new lineage version", async () => {
  const asset = imageAsset();
  const { calls, deps } = makeDeps(asset);

  const media = await regenerateImageAsset({
    workspaceId: "ws-1",
    assetId: asset.id,
    deps,
  });

  assert.equal(calls.generateImage?.prompt, "a saved prompt");
  assert.equal(calls.generateImage?.provider, "openai");
  assert.equal(calls.generateImage?.model, "gpt-image-1.5");
  // applyMedia anchors on the source asset id (it reads that row's lineage to
  // insert the next version), with the live bucket set.
  assert.equal(calls.applyMedia?.assetId, asset.id);
  assert.equal(calls.applyMedia?.update.storageBucket, "popcornready-assets-public");
  assert.equal((calls.applyMedia?.update.provenance as { prompt: string }).prompt, "a saved prompt");
  // New bytes carry a fresh content hash so graph consumers see content changed.
  assert.equal(typeof calls.applyMedia?.update.contentHash, "string");
  assert.ok((calls.applyMedia?.update.contentHash as string).length > 0);
  assert.equal(media.url, "https://cdn.example/new.png");
});

test("writes to the private bucket when the project is private", async () => {
  // Asset row says "public" but the project is private: effective visibility is
  // private, so regenerated bytes must not be published to the public bucket.
  const asset = imageAsset({ visibility: "public" });
  const { calls, deps } = makeDeps(asset, "private");

  await regenerateImageAsset({ workspaceId: "ws-1", assetId: asset.id, deps });

  assert.equal(calls.writeObject?.visibility, "private");
  assert.equal(calls.applyMedia?.update.storageBucket, "popcornready-assets-private");
});

test("a caller-supplied prompt wins over the saved one and is persisted", async () => {
  const asset = imageAsset();
  const { calls, deps } = makeDeps(asset);

  await regenerateImageAsset({
    workspaceId: "ws-1",
    assetId: asset.id,
    prompt: "  a brand new prompt  ",
    deps,
  });

  assert.equal(calls.generateImage?.prompt, "a brand new prompt");
  assert.equal((calls.applyMedia?.update.provenance as { prompt: string }).prompt, "a brand new prompt");
});

test("throws prompt_required when no prompt is saved or provided", async () => {
  const asset = imageAsset({ provenance: undefined });
  const { deps } = makeDeps(asset);

  await assert.rejects(
    regenerateImageAsset({ workspaceId: "ws-1", assetId: asset.id, deps }),
    (err: unknown) => err instanceof ApiError && err.code === "prompt_required"
  );
});

test("rejects non-image assets with asset_invalid", async () => {
  const asset = imageAsset({ kind: "video" });
  const { deps } = makeDeps(asset);

  await assert.rejects(
    regenerateImageAsset({ workspaceId: "ws-1", assetId: asset.id, deps }),
    (err: unknown) => err instanceof ApiError && err.code === "asset_invalid"
  );
});
