import { createHash } from "crypto";
import type {
  CharacterProfile,
  CharacterReference,
  GeneratedAssetCharacterBinding,
} from "@popcorn/shared/types";
import type { CharacterGenerationContext } from "@popcorn/shared/generative/types";

export interface OneShotCharacterDraft {
  profile: CharacterProfile;
  reference: CharacterReference;
}

export function describeRecurringCharacter(goal: string): {
  age: string;
  role: string;
  description: string;
  identityInvariants: string;
  wardrobeInvariants: string;
  negativePrompt: string;
} {
  const ageMatch = goal.match(/\b(\d{1,2})[- ]year[- ]old\b/i);
  const age = ageMatch ? `${ageMatch[1]}-year-old` : "same-age";
  const roleMatch = goal.match(
    /\b(?:\d{1,2}[- ]year[- ]old\s+)?([a-z][a-z -]{1,40}?(?:boy|girl|child|kid|man|woman|filmmaker|creator|founder|teacher|student))\b/i
  );
  const role = roleMatch ? roleMatch[1].trim() : "main character";
  const subject = `${age} ${role}`;

  return {
    age,
    role,
    description: `Recurring protagonist from the one-shot brief: ${subject}.`,
    identityInvariants: [
      `The protagonist must remain the same ${subject} across every generated shot.`,
      "Preserve the same face, apparent age, hair, build, silhouette, skin tone, and emotional throughline.",
      "Dream, future, famous, or imagined versions must still read as the same protagonist, not a recast person.",
    ].join(" "),
    wardrobeInvariants:
      "Keep a recognizable wardrobe anchor from the hero reference unless the shot explicitly requires a costume change.",
    negativePrompt:
      "Do not redesign, recast, age-shift, gender-swap, replace, or turn the protagonist into an unrelated person.",
  };
}

export function buildOneShotCharacterDraft(input: {
  goal: string;
  projectId: string;
  profileId: string;
  referenceId: string;
  assetId: string;
  now: string;
}): OneShotCharacterDraft {
  const character = describeRecurringCharacter(input.goal);
  const profile: CharacterProfile = {
    id: input.profileId,
    projectId: input.projectId,
    name: "One-shot protagonist",
    description: character.description,
    identityInvariants: character.identityInvariants,
    wardrobeInvariants: character.wardrobeInvariants,
    negativePrompt: character.negativePrompt,
    status: "ready",
    createdAt: input.now,
    updatedAt: input.now,
  };

  return {
    profile,
    reference: {
      id: input.referenceId,
      characterProfileId: profile.id,
      assetId: input.assetId,
      role: "hero_frame",
      quality: "approved",
      notes: "Generated by one-shot as the recurring protagonist hero reference.",
    },
  };
}

export function oneShotHeroFramePrompt(input: {
  goal: string;
  style: string;
}): string {
  const character = describeRecurringCharacter(input.goal);
  return [
    "Create one clean cinematic hero-frame image to use as a recurring character reference for video generation.",
    `Subject: the same ${character.age} ${character.role} from this story.`,
    `Story context: ${input.goal}`,
    `Visual style: ${input.style}.`,
    "Show the protagonist clearly with a recognizable face, hair, build, silhouette, skin tone, and a simple wardrobe anchor.",
    "Use natural cinematic lighting and a realistic live-action look. No text, logos, captions, watermarks, or extra main characters.",
  ].join(" ");
}

export function oneShotPromptInvariantVersion(profile: CharacterProfile): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        id: profile.id,
        identityInvariants: profile.identityInvariants,
        styleInvariants: profile.styleInvariants || "",
        wardrobeInvariants: profile.wardrobeInvariants || "",
        negativePrompt: profile.negativePrompt || "",
      })
    )
    .digest("hex")
    .slice(0, 12);
}

export function oneShotCharacterContext(input: {
  profile: CharacterProfile;
  reference: CharacterReference;
  referencePath: string;
  referenceUrl: string;
  originalPrompt: string;
  providerPrompt: string;
}): CharacterGenerationContext {
  return {
    profiles: [input.profile],
    references: [
      {
        reference: input.reference,
        assetId: input.reference.assetId,
        path: input.referencePath,
        url: input.referenceUrl,
      },
    ],
    consistencyMode: "hero_frame",
    promptInvariantVersion: oneShotPromptInvariantVersion(input.profile),
    originalPrompt: input.originalPrompt,
    shotDelta: { prompt: input.providerPrompt },
  };
}

export function oneShotCharacterBinding(input: {
  assetId: string;
  context: CharacterGenerationContext;
  providerSettings?: GeneratedAssetCharacterBinding["providerSettings"];
}): GeneratedAssetCharacterBinding {
  return {
    assetId: input.assetId,
    characterProfileIds: input.context.profiles.map((profile) => profile.id),
    referenceIds: input.context.references.map(({ reference }) => reference.id),
    consistencyMode: input.context.consistencyMode,
    originalPrompt: input.context.originalPrompt,
    promptInvariantVersion: input.context.promptInvariantVersion,
    providerSettings: input.providerSettings,
  };
}
